version: "3.8"


services:

  expensesapp:
    build:    
      context: ./
    container_name: expensesapp_container
    networks:
      - expensesapp_network
    ports:
      - "8080:8080" 
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_PASSWORD: Test@123
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - expensesapp_network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: expenses_tracker
    volumes:
      - expensesapp_volume:/var/lib/mysql
    restart: always

  nginx:
    build:
      context: ./nginx/
    container_name: nginx_container
    ports:
      - "80:80"
    networks:
      - expensesapp_network
    restart: always
    depends_on:
      - expensesapp

networks:
  expensesapp_network:
    driver: bridge

volumes:
  expensesapp_volume:
